---
# Source: cloudgeeks/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-cloudgeeks
  namespace: default
  labels:
    app.kubernetes.io/name: cloudgeeks
    app.kubernetes.io/instance: app    
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: cloudgeeks
    app.kubernetes.io/instance: app 
---
# Source: cloudgeeks/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cloudgeeks
  namespace: default
  labels:
    app.kubernetes.io/name: cloudgeeks
    app.kubernetes.io/instance: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudgeeks
      app.kubernetes.io/instance: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudgeeks
        app.kubernetes.io/instance: app
    spec:
      securityContext:
        {}
      containers:
        - name: cloudgeeks
          securityContext:
            {}
          image: "quickbooks2018/blue:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: cloudgeeks/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "app-cloudgeeks-test-connection"
  namespace: default
  labels:
    app.kubernetes.io/name: cloudgeeks
    app.kubernetes.io/instance: app
    
    
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['app-cloudgeeks:80']
  restartPolicy: Never
